plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

url: OldNewTimer.github.io
baseurl: /myreponame

# Google Analytics
google_analytics: G-FLTP85BKSJ

collections:
  programs:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "programs"
    values:
      layout: "program"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Markdown to HTML recognizes newlines and not just paragraphs.
kramdown:
  hard_wrap: true